### ISSUE TITLE
Backspace closes connection.

### ISSUE THREAD

**Issue by sastephe** [ianepperson/telnetsrvlib#15]
Hi I have been running the sample code but when I type a backspace the connection closes with a TypeError. I was wondering if I could be given a hint on how I may want to fix this. Thank you for your help. Sam

**Comment by sastephe** [comment]
This is the traceback that I get when I try to use the backspace ...

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\gevent\greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "C:\Anaconda\lib\site-packages\telnetsrv\telnetsrvlib.py", line 494, in streamserver_handle
    cls(request, address, server)
  File "C:\Anaconda\lib\site-packages\telnetsrv\green.py", line 14, in __init__
    TelnetHandlerBase.**init**(self, request, client_address, server)
  File "C:\Anaconda\lib\site-packages\telnetsrv\telnetsrvlib.py", line 481, in **init**
    SocketServer.BaseRequestHandler.**init**(self, request, client_address, server)
  File "C:\Anaconda\lib\SocketServer.py", line 649, in **init**
    self.handle()
  File "C:\Anaconda\lib\site-packages\telnetsrv\telnetsrvlib.py", line 984, in handle
    raw_input = self.readline(prompt=self.PROMPT).strip()
  File "C:\Anaconda\lib\site-packages\telnetsrv\telnetsrvlib.py", line 703, in readline
    self._readline_echo(self.CODES['CSRLEFT'] + self.CODES['DEL'], echo)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
<Greenlet at 0x270b800L: <bound method classobj.streamserver_handle of <class __main__.MyTelnetHandler at 0x000000000273
7348>>(<socket at 0x2750668L fileno=332 sock=127.0.0.1:80, ('127.0.0.1', 56100))> failed with TypeError
