### ISSUE TITLE
Fails on Python3.4.2

### ISSUE THREAD

**Issue by gmatesunny** [ianepperson/telnetsrvlib#22]
```
roshanmk@roshanmk-train ~ $ python3
Python 3.4.2 (default, Oct  8 2014, 13:14:40) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from telnetsrv.threaded import TelnetHandler, command
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/telnetsrv/threaded.py", line 8, in <module>
    from telnetsrvlib import TelnetHandlerBase, command
ImportError: No module named 'telnetsrvlib'
>>> 

```

```
roshanmk@roshanmk-train ~ $ sudo -H pip3 install telnetsrv
Requirement already satisfied: telnetsrv in /usr/local/lib/python3.4/dist-packages (0.4)
```

**Comment by fenglwh** [comment]
this may fixed by change
from telnetsrvlib import TelnetHandlerBase, command
to:
from .telnetsrvlib import TelnetHandlerBase, command

**Comment by fenglwh** [comment]
to solve the No module named 'SocketServer' error:

import sys
if sys.version_info.major ==3:
    import socketserver as SocketServer
else:
    import SocketServer

**Comment by sambonator** [comment]
Are these Bugs in the telnetsrv library?

**Comment by AmansGit** [comment]
> to solve the No module named 'SocketServer' error:
> 
> import sys
> if sys.version_info.major ==3:
>     import socketserver as SocketServer
> else:
>     import SocketServer

In which file do we need to write this?
